- alias: "Turn on light if value exceeds 100"
  trigger:
    - platform: state
      entity_id: input_number.light_control
  condition:
    - condition: numeric_state
      entity_id: input_number.light_control
      above: 100
  action:
    - service: switch.turn_on
      entity_id: switch.smart_socket_socket

- alias: "Turn off light if value is 100 or less"
  trigger:
    - platform: state
      entity_id: input_number.light_control
  condition:
    - condition: numeric_state
      entity_id: input_number.light_control
      below: 101
  action:
    - service: switch.turn_off
      entity_id: switch.smart_socket_socket

- alias: "Toggle Smart Socket Every Minute"
  trigger:
    - platform: time_pattern
      seconds: "/10" # Triggers every 5 seconds
  action:
    - service: switch.toggle
      entity_id: switch.smart_socket_socket
