# Loads default set of integrations. Do not remove.
default_config:
logger:
  default: info

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
python_script:

bluetooth:

# Example configuration.yaml entry
panel_custom:
  - name: my-panel
    sidebar_title: TodoMVC
    sidebar_icon: mdi:work
    url_path: my-todomvc
    module_url: /local/my-panel.js
    config:
      who: world

switch:
  - platform: command_line
    switches:
      my_command:
        command_on: "bash /config/scripts/my_script.sh"
        friendly_name: "Run My Command"

input_number:
  light_control:
    name: "Light Control"
    initial: 50
    min: 0
    max: 200
    step: 1
#example custom rest entity
#sensor:
#  - platform: rest
#    name: Computer Temperature
#    resource: http://<ip>:<port>/get_data
#    method: GET
#    scan_interval: 60 # How often to update the sensor (in seconds)
#    value_template: "{{ value_json.temperature }}"
#    unit_of_measurement: "°C" # Adjust as needed
#    json_attributes:
#      - humidity
